### PR TITLE
BUGFIX: Use correct NodeIndexerInterface in command controller

### PR DESCRIPTION
**Pull request by kdambekalns**
Fixes Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor#208

### CODE REVIEW

**Comment by kitsunet** [comment]
Wait, but why is master not Neos\ContentRepository?

**Comment by kdambekalns** [comment]
It is, but the target branch for this was wrong, oh so wrong. Now it is better.

**Comment by kdambekalns** [comment]
Hah! Travis 0 – me 1!

**Comment by kitsunet** [comment]
Win for Karsten 😆

**Pull request merged**
