### PR TITLE
BUGFIX: Fix error handling

### PR DESCRIPTION
**Pull request by kdambekalns**

### CODE REVIEW

**Comment by daniellienert** [comment]
👍🏼

**Comment by kdambekalns** [comment]
@daniellienert Is that consciously not a formal review, or …?

**Comment by daniellienert** [comment]
@kdambekalns thats a read-the-code-on-my-phone-app-which-has-no-review-button kind of a review :)

**Comment by kdambekalns** [comment]
@daniellienert Ah, ok. But… there is a review button on mobile, under the changes tab. At the bottom:
img_feeb0c9b66d7-1

**Pull request merged**
