### PR TITLE
FEATURE: Allow modifying requests in arbitrary ways by using request()

### PR DESCRIPTION
**Pull request by skurfuerst**

### CODE REVIEW

**Comment by johannessteu** [comment]
👍  by reading

**Comment by kdambekalns** [comment]
Please make sure to coordinate with #114 - sounds as if there is potential for conflict

**Comment by kdambekalns** [comment]
But, looks good by reading…

**Comment by dfeyer** [comment]
I can rebase #114 when this one is merged, the other PR is breaking anyway so should way the next major.

**Pull request merged**
