### PR TITLE
BUGFIX: Include the context document in the query result

### PR DESCRIPTION
**Pull request by dfeyer**
The ElasticSearchQueryBuilder::query searches only below the given context
document.

One example when this is wrong is when you search from the site node, which
you use as the homepage - in this case the actual "homepage" would not be
searched.

### CODE REVIEW

**Comment by dfeyer** [comment]
Don't merge this one in the 2.0 branch, the query syntax is only supported by 2.0+ :(

**Comment by dfeyer** [comment]
I force push a fix to support ES 1.7 -> 2.4, basically minimum_should_match was not needed because the default value is 1

**Comment by hoodini** [comment]
made composer update with neos and used this changes directly to Flowpack.ElasticSearch.ContentRepositor, it works perfect!

**Comment by dimaip** [comment]
@dfeyer I can verify that this PR fixes the bug. But why are the tests failing?

**Comment by dfeyer** [comment]
@dimaip Because the query structure is not the same I push a fix, and we can merge this one as soon as travis is green and release a minor version

**Comment by kdambekalns** [comment]
Took the freedom to edit title and description a  bit. And I dare to oppose - you do specify the _context node_, below which you want to search. That's how it worked so far.

Now this would change the behaviour, potentially doing awkward things to search results. No?

As far as I understand, the "site node is the homepage" is kind of an edge case here…

**Comment by dfeyer** [comment]
Right ...

**Comment by dfeyer** [comment]
Retargeted to master, test will fail before merging #118

**Comment by dfeyer** [comment]
@kdambekalns If we document this change in the release note of the next major (3.0) is it OK for you ? We can even document how to get back to the old behaviour by adding a filter to ignore the current node ?

**Comment by kdambekalns** [comment]
Sure, no problem then.

**Comment by kdambekalns** [comment]
So, happily updated to 3.0 and was disappointed, since this still didn't work. Checked the code, and the inclusion of the context node into the search is not in the 3.0 codebase. It probably got lost during the driver rewrite?!

Any insights, @dfeyer or @daniellienert maybe?

**Comment by daniellienert** [comment]
@kdambekalns: Sorry, that one slipped through. The tests in current master asserts 3 nodes whereas there should be 4.

**Comment by kdambekalns** [comment]
Now, what do we do? This change was pushed back to 3.0, since it was considered breaking. Now 3.0 and 4.0 are released, does this mean it has to go into 5.0?

**Comment by kitsunet** [comment]
So, uhm, How is site node being the homepage an edge case? It's the default we deliver with neos, so it's certainly not an edge case.

I consider this a serious bug. How about introducing a second argumetn to `query` enabling this and immediately deprecating this flag to be defaulted to true and then removed in next major.

**Comment by kdambekalns** [comment]
Edge case: most sites I know make the site node a shortcut, to ease navigation building. But whatever, that's no longer important. ;)

A flag? Hm, not very elegant.

**Comment by kdambekalns** [comment]
@dfeyer suggested

> We can even document how to get back to the old behaviour by adding a filter to ignore the current node ?

How would that filter look like?

**Pull request merged**
