### PR TITLE
TASK: Allow to set Filter execution for terms filter type

### PR DESCRIPTION
**Pull request by dfeyer**

### CODE REVIEW

**Comment by aertmann** [comment]
:+1: by reading

**Comment by dfeyer** [comment]
Will rebase this on top of https://github.com/Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor/pull/114 when it's merged

**Comment by daniellienert** [comment]
:+1: by reading
It would be cool if you could extend the ElasticSearchQueryBuilderTest with this option.

**Comment by dfeyer** [comment]
Not sure if this is really needed as #114 offer more flexibility without making the API more complexe.

**Comment by kdambekalns** [comment]
Well, not sure either. Is what this tries to solve also possible now (with #114 merged)? Then we should just close this one…

**Comment by dfeyer** [comment]
@kdambekalns I agree, we can close this one

**Pull request closed without merging**
