### PR TITLE
[WIP] [Task] Better dimension support

### PR DESCRIPTION
**Pull request by dfeyer**
This change force the NodeIndexer to update the current node in all available dimensions combination to be sure ES index are correct.

### CODE REVIEW

**Comment by fanat98** [comment]
:+1:
Onlly Number of nodes by nodeindex:buld is always 1 

Workspace "user-admin" and dimensions "{"language":["fr"]}" done. (Indexed 1 nodes)
Workspace "user-admin" and dimensions "{"language":["de"]}" done. (Indexed 126 nodes)

**Comment by dfeyer** [comment]
Will push a follow up during the week-end with PSR2 polishing

**Comment by dfeyer** [comment]
Sorry delete the git branch ... by accident, continue to work on:
https://github.com/Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor/tree/tast-better-dimensions
Check the last commit

**Comment by dfeyer** [comment]
The new PR https://github.com/Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor/pull/108

**Comment by dfeyer** [comment]
@fanat98 Can you test the new PR

About the output of the comment it's the truth ;)

Onlly Number of nodes by nodeindex:buld is always 1

> Workspace "user-admin" and dimensions "{"language":["fr"]}" done. (Indexed 1 nodes)
> Workspace "user-admin" and dimensions "{"language":["de"]}" done. (Indexed 126 nodes)

You have only one nodes in french, but internally all nodes are indexed in all possible dimensions combinations.

**Pull request closed without merging**
